In [1]:
import numpy as np
array1D=np.array([1,2,3,4])
print(array1D)


[1 2 3 4]


In [2]:
# Creating a 2D array
import numpy as np
array_2d = np.array([[1, 2, 3], [4, 5, 6]])
print("2D Array:\n", array_2d)


arr_oje=np.array([1,"two",[3,1,9],{1:"mango"},8], dtype=object)
print("\n",arr_oje.dtype)
print("\n",arr_oje)

print(arr_oje[1])
print(arr_oje[2])





2D Array:
 [[1 2 3]
 [4 5 6]]

 object

 [1 'two' list([3, 1, 9]) {1: 'mango'} 8]
two
[3, 1, 9]


In [3]:
# Creating a 2D array
import numpy as np

arr1 = np.array([3,4,5,6])
arr2 = np.array([4,6,8,2])
arr3 = arr1 + arr2  # element wise addition vectorized
print(arr3)

arr4 = arr1 * arr2  # elemnt wise multiplucation of vetorized
print(arr4)

arr4 = arr1 + 2   # scalar opreation vactorized
print("scalar opreation : ",arr4)
  

[ 7 10 13  8]
[12 24 40 12]
scalar opreation :  [5 6 7 8]


In [22]:
# Creating a 2D array
import numpy as np

arr1 = np.array([3,4,5,6])
arr2 = np.array([4,6,8,2])
arr3 = arr1 + arr2  # element wise addition vectorized
print(arr3)

arr4 = arr1 * arr2  # elemnt wise multiplucation of vetorized
print(arr4)

arr4 = arr1 + 2   # scalar opreation vactorized
print("scalar opreation : ",arr4)
  

[ 7 10 13  8]
[12 24 40 12]
scalar opreation :  [5 6 7 8]


In [2]:
# performing opretion on scalar and array roadcasting
import numpy as np
arr1 = np.array([3,4,5,6])
scalar = 3
result = arr1 + scalar
print(result)


  

[6 7 8 9]


In [3]:
import numpy as np


In [4]:
arr=np.array([2,3,4,5])
print(arr)

[2 3 4 5]


In [5]:
type(arr)

numpy.ndarray

In [7]:
arr_2d= np.array([[1,3,4],[3,4,5]])
print(arr_2d)
arr_2d

[[1 3 4]
 [3 4 5]]


array([[1, 3, 4],
       [3, 4, 5]])

In [15]:
arr3 = np.zeros((2,3))
arr3


array([[0., 0., 0.],
       [0., 0., 0.]])

In [17]:
arr=np.ones([2,3])
arr

array([[1., 1., 1.],
       [1., 1., 1.]])

In [165]:
arr=np.identity(4)
arr

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [25]:
arr=np.arange(6,16,2)
arr

array([ 6,  8, 10, 12, 14])

In [31]:
arr=np.linspace(3,9,5)
print(arr)

[3.  4.5 6.  7.5 9. ]


In [32]:
a2=arr.copy()
a2

array([3. , 4.5, 6. , 7.5, 9. ])

In [39]:
arr4=np.array([[[1,2],[3,4],[5,6],[2,4]]])
arr4.shape
arr4.ndim
# print(arr4)

3

In [41]:
li=range(100)
arr1=np.arange(100)
li


range(0, 100)

In [42]:
import sys 
print(sys.getsizeof(87)* len(li))

2800


In [44]:
print(arr1.itemsize *arr1.size)

32


In [47]:
import time 

x=range(10000000)
y=range(10000000,20000000)
start_time=time.time()

c=[(x,y) for x,y in zip(x,y)]
print(time.time() -start_time)

1.2622761726379395


In [48]:
a2=np.arange(10000000)
a3=np.arange(10000000)
start_time=time.time()
c= a2+a3
print(time.time()-start_time)

0.36186838150024414


In [57]:
arr=np.arange(24).reshape(6,4)
arr


array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [75]:
arr[4:6:,2:4]   # slicing

array([[18, 19],
       [22, 23]])

In [76]:
# iteration
for i in arr:
    print(i)

[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]
[12 13 14 15]
[16 17 18 19]
[20 21 22 23]


In [78]:
for i in np.nditer(arr):
    print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23


In [81]:
ar1=np.array([3,4,5,5,6])
ar2=np.array([8,9,0,3,2])
ar1-ar2

array([-5, -5,  5,  2,  4])

In [84]:
ar1 * 2  # scalar multiplication

array([ 6,  8, 10, 10, 12])

In [ ]:
ar1 * ar2 # vectore multiplication

In [85]:
ar1 > 2

array([ True,  True,  True,  True,  True])

In [93]:
a =np.arange(6).reshape(2,3)
c= np.arange(6).reshape(3,2)

a.dot(c)
c

array([[0, 1],
       [2, 3],
       [4, 5]])

In [99]:
c.max(axis =1)

array([1, 3, 5])

In [104]:
c.sum(axis=1)
c.mean()

2.5

In [108]:
np.sin(a)
np.std(c)
np.exp(c)

array([[  1.        ,   2.71828183],
       [  7.3890561 ,  20.08553692],
       [ 54.59815003, 148.4131591 ]])

In [128]:
np.random.random()


0.7203244934421581

In [129]:
np.random.seed(1)
np.random.random()

0.417022004702574

In [134]:
np.random.uniform(1,100, 11)  # random value 

array([ 3.71137173, 67.37628351, 42.31317543, 56.31029302, 14.89830692,
       20.61204742, 80.2737123 , 96.857896  , 32.02899364, 69.53993895,
       87.76252608])

In [135]:
np.random.uniform(1,100,10).reshape(2,5)

array([[89.56605969,  9.41937693,  4.86642354, 17.81321154, 87.93610784],
       [10.73633655, 42.68965488, 95.83106348, 53.78336321, 69.49583428]])

In [143]:
np.random.randint(1,10,15).reshape(3,5)    # 2D array using random 

array([[9, 5, 1, 2, 9],
       [3, 4, 2, 3, 8],
       [3, 7, 1, 3, 7]])

In [161]:
ar=np.random.randint(1,10,6)
np.where(ar%2==1,-1, ar)


array([-1, -1, -1, -1,  4,  4])

In [164]:
ar1=np.array([9,3,4,5,5,6])
ar1.sort()
ar1

array([3, 4, 5, 5, 6, 9])

In [170]:
arr= np.arange(6)
arr
arr.reshape(2,3)

array([[0, 1, 2],
       [3, 4, 5]])