In [90]:
# reshaping numpy array

import numpy as np

arr4 = np.array([[4,5,6,7],[3,5,6,7]])
ar= np.arange(5)

arr4.ndim
arr4.ravel()
np.ravel(arr4)
arr4

array([[4, 5, 6, 7],
       [3, 5, 6, 7]])

In [12]:
arr5 = np.array([[4,5,6,2],[1,1,1,1]])  # horisntal add
np.hstack((arr4,arr5))

array([[4, 5, 6, 7, 4, 5, 6, 2],
       [3, 5, 6, 7, 1, 1, 1, 1]])

In [18]:
np.vstack((arr4,arr5))  # vertically add

np.hsplit(arr5,4)  # horigently split

[array([[4],
        [1]]),
 array([[5],
        [1]]),
 array([[6],
        [1]]),
 array([[2],
        [1]])]

In [17]:
np.vsplit(arr5,2)

[array([[4, 5, 6, 2]]), array([[1, 1, 1, 1]])]

In [27]:
a2= np.arange(24).reshape(6,4)
a2


array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [31]:
a2[[0,2,4]] # fancy indexing 

a2[a2>15 ]  #in dexing using oolean array also filter

array([16, 17, 18, 19, 20, 21, 22, 23])

In [37]:
a2[(a2>15) & (a2%2==0)]  # only value that satisfy condition

array([16, 18, 20, 22])

In [41]:
a2[(a2>15) & (a2%2==0)]=0
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [ 0, 17,  0, 19],
       [ 0, 21,  0, 23]])

In [49]:
a3 =np.array([4])
a2 + a3 

array([[ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [ 4, 21,  4, 23],
       [ 4, 25,  4, 27]])

In [51]:
a1=np.empty((2,3))
a1

array([[2.0e-323, 2.5e-323, 4.0e-323],
       [4.4e-323, 0.0e+000, 4.0e-323]])

In [57]:
A=np.array([3,4,5,1,10])
C=np.array([30,40,50,60,0])
A @ C
A = np.array([[1, 1],
              [0, 1]])
B = np.array([[2, 0],
              [3, 4]])
A @ B

560

In [85]:
ar= np.random.uniform(0,1,6).reshape(2,3)
ar
ar2= np.ones((2,3), dtype=int)
ar2*3

array([[0.08421878, 0.48755659, 0.71950582],
       [0.3783436 , 0.59489875, 0.59522381]])

In [83]:
import numpy as np

rg = np.random.default_rng(1)  # Create instance of default random number generator


array([[1, 1, 1],
       [1, 1, 1]])

In [80]:
ar += ar2
ar

array([[3.53470257, 3.5758982 , 3.10976753],
       [3.01978224, 3.81614505, 3.51793342]])

In [89]:
import numpy as np

# Define the value of pi
pi = np.pi

# Generate an array with 3 values evenly spaced between 0 and pi
b = np.linspace(0, pi, 30)

# Print the array
print(b)


[0.         0.10833078 0.21666156 0.32499234 0.43332312 0.54165391
 0.64998469 0.75831547 0.86664625 0.97497703 1.08330781 1.19163859
 1.29996937 1.40830016 1.51663094 1.62496172 1.7332925  1.84162328
 1.94995406 2.05828484 2.16661562 2.2749464  2.38327719 2.49160797
 2.59993875 2.70826953 2.81660031 2.92493109 3.03326187 3.14159265]
